<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-D36JS0L" name="com.mercuryTravels.testBranchAddress" tests="3" failures="1" timestamp="15 Aug 2018 18:09:37 GMT" time="44.278" errors="0">
  <testcase name="testBranchAddress" time="17.437" classname="com.mercuryTravels.testBranchAddress"/>
  <testcase name="testBranchAddress" time="13.220" classname="com.mercuryTravels.testBranchAddress">
    <failure type="java.lang.AssertionError" message="expected [Mercury Travels Ltd.
125, Infantry Road, Bangalore 560 001.xxx] but found [Mercury Travels Ltd.
125, Infantry Road, Bangalore 560 001.]">
      <![CDATA[java.lang.AssertionError: expected [Mercury Travels Ltd.
125, Infantry Road, Bangalore 560 001.xxx] but found [Mercury Travels Ltd.
125, Infantry Road, Bangalore 560 001.]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.mercuryTravels.testBranchAddress.testBranchAddress(testBranchAddress.java:48)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
    </failure>
  </testcase> <!-- testBranchAddress -->
  <testcase name="testBranchAddress" time="13.621" classname="com.mercuryTravels.testBranchAddress"/>
</testsuite> <!-- com.mercuryTravels.testBranchAddress -->
